<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDown_RowperPage</name>
   <tag></tag>
   <elementGuidId>749af496-00c7-4104-be8b-3dec7c3ad3cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.pagination-input--dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagination']/nav/ul/li[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8cac1ed-84db-4cb7-92c1-33b4c5831fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-input--dropdown</value>
      <webElementGuid>2b7cb75c-2829-4ebc-b1b7-6f948a74681f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51020</value>
      <webElementGuid>1b4332a1-e404-4c75-a8ed-5ede66852fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination&quot;)/nav[1]/ul[@class=&quot;pagination justify-content-end m-0&quot;]/li[@class=&quot;page-item mx-1&quot;]/select[@class=&quot;pagination-input--dropdown&quot;]</value>
      <webElementGuid>11356b33-2893-477d-8cef-2740c768cdbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination']/nav/ul/li[2]/select</value>
      <webElementGuid>94fad0d1-1863-4ed4-85b8-3589e463b45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows Per Page'])[1]/following::select[1]</value>
      <webElementGuid>92ff9d9c-614b-4fc0-baa3-0f22fb3bc661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3d1ccd0a-2f83-443f-9d53-550d31a83858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '51020' or . = '51020')]</value>
      <webElementGuid>bf4ee85d-df5a-42fa-9623-45e746e08786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
