<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_input-tableSearch--style</name>
   <tag></tag>
   <elementGuidId>d05374af-8e8e-4fca-84de-eb121fcac3c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-tableSearch--style</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b574f80f-504d-4ef2-bb64-2a5ceb9cdb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-tableSearch--style</value>
      <webElementGuid>370234ef-f2b0-437b-81ba-8f7e5b8f94b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b31a7f60-c58f-409d-a503-ac68dce84f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name, Email, CC ID </value>
      <webElementGuid>cbc87fc5-f602-44c4-8b74-e7fa23dd262f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7c8691fd-7823-45d4-872d-4b3ad9d6e960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;body-side--container  wrapper&quot;]/div[@class=&quot;body-main--container&quot;]/div[@class=&quot;body-tablesearch--container&quot;]/div[@class=&quot;row justify-content-between py-1&quot;]/div[@class=&quot;col-9 col-md-6&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-9&quot;]/div[@class=&quot;row m-0 table-search--container d-flex justify-content-center&quot;]/div[@class=&quot;col-11 px-1&quot;]/input[@class=&quot;input-tableSearch--style&quot;]</value>
      <webElementGuid>e54f2e2a-d1b4-406a-afed-a4cc7789c3d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>4e7eb3f9-2240-4274-8848-b7941f55ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>75d7af13-6d8a-49ac-b033-62cec4ac6550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3894e342-3ae5-4604-b698-ca6a3d3627e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Name, Email, CC ID ']</value>
      <webElementGuid>25b17db5-8cd0-4806-8926-269ae078cdf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
