<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_51020</name>
   <tag></tag>
   <elementGuidId>e965d94e-3ea8-4284-8964-fb89b610a1ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagination']/nav/ul/li[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.pagination-input--dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72334a9f-3749-451d-a8ec-ee52d28a6ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-input--dropdown</value>
      <webElementGuid>73bbbe4e-f50b-410d-89b2-b5fab7c42003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51020</value>
      <webElementGuid>f4c74981-8545-4302-90f5-b05c0890f949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination&quot;)/nav[1]/ul[@class=&quot;pagination justify-content-end m-0&quot;]/li[@class=&quot;page-item mx-1&quot;]/select[@class=&quot;pagination-input--dropdown&quot;]</value>
      <webElementGuid>b242d82a-da9b-4f0b-9cec-3c1af167c179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination']/nav/ul/li[2]/select</value>
      <webElementGuid>e4b3d9f0-1fce-47cc-81ad-ec8bb00fddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows Per Page'])[1]/following::select[1]</value>
      <webElementGuid>4a54f420-0da0-41df-987e-adff4ae193c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2b6e07c4-0503-4fbf-a90a-cdf4f862b560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '51020' or . = '51020')]</value>
      <webElementGuid>f50e3e94-6adb-4b70-a710-3d1b0eda0efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
