<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TableData_MemberName</name>
   <tag></tag>
   <elementGuidId>14cdfa6a-4001-40ee-b13b-3cb93f88a147</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/table/tbody/tr[2]/td/div[2]/div[2]/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d2c45d3-5568-4908-b9f4-e8c238baeca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize</value>
      <webElementGuid>03e1a179-28d6-4f61-86aa-10fd1ae64b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mark Waltor</value>
      <webElementGuid>b35f2c5b-1ed7-4802-9ebd-befd4bf63b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;body-side--container  wrapper&quot;]/div[@class=&quot;body-main--container&quot;]/div[@class=&quot;tableContainer-outer-container&quot;]/table[@class=&quot;table-responsive-sm mt-4 table-container responsiveTable&quot;]/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;col&quot;]/td[@class=&quot;table-head--width frozen-column text-wrap pivoted box-shadow-none&quot;]/div[@class=&quot;row justify-content-center undefined&quot;]/div[@class=&quot;col-8 p-0&quot;]/p[@class=&quot;p-0 my-2 regular-table-text&quot;]/span[@class=&quot;text-capitalize&quot;]</value>
      <webElementGuid>59f5c1f7-f03a-4734-aad0-b0cc9f99a71f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/table/tbody/tr[2]/td/div[2]/div[2]/p/span</value>
      <webElementGuid>416532f3-a11e-4e86-bc24-cb4a7dc1736f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[2]/following::span[1]</value>
      <webElementGuid>5b2b1829-4186-4643-8d0f-ca29e24af686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senior'])[2]/preceding::span[1]</value>
      <webElementGuid>4da6e8f6-914f-434e-b93a-feb5b5fe1829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note'])[3]/preceding::span[5]</value>
      <webElementGuid>eb0f69f5-3151-40cb-93ea-f4545f102a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div[2]/div[2]/p/span</value>
      <webElementGuid>3719f49b-840a-41b1-b386-20cbee467a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mark Waltor' or . = 'Mark Waltor')]</value>
      <webElementGuid>cc3deef0-2b77-4d15-8298-dfbe27cb67e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
