<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextBox_Email</name>
   <tag></tag>
   <elementGuidId>44f1d5b7-a3df-4dfa-a99c-35397a37b9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a17eaada-203d-400c-a286-23a4df44aa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-tableSearch--style</value>
      <webElementGuid>7f871a77-808b-41e9-be9f-7525e0fe68ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aa562c8-99b2-48dd-9031-6a1c00120f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>abc@gmail.com</value>
      <webElementGuid>2f583663-2b60-40f0-8a21-6644122cbc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>5ac1c8fd-1ae1-4950-aede-c4d2f25abfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;body-side--container  wrapper&quot;]/div[@class=&quot;body-main--container&quot;]/div[@class=&quot;tableContainer-outer-container&quot;]/table[@class=&quot;table-responsive-sm mt-4 table-container responsiveTable&quot;]/thead[@class=&quot;table-header&quot;]/tr[@class=&quot;col&quot;]/th[@class=&quot;p-0  table-head--width&quot;]/div[@class=&quot;thead-form--container&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;col-md-auto&quot;]/div[@class=&quot;row table-head-search--container d-flex justify-content-center bg-white&quot;]/div[@class=&quot;col-10 px-2&quot;]/input[@class=&quot;input-tableSearch--style&quot;]</value>
      <webElementGuid>158013a1-e556-4d18-886f-ac33009cfe0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>205821f6-2075-471e-9608-dd79f0c980da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/table/thead/tr/th[4]/div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>4820ce7f-b610-48ac-a8a0-aad397b7d23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>bcabb778-b4d7-4781-b631-b90f885a53fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'abc@gmail.com']</value>
      <webElementGuid>23a416f8-c5c6-4ab7-b71d-e20e8072875b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
