<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextBox_CCID</name>
   <tag></tag>
   <elementGuidId>0fb1e1b2-319b-4864-a7bf-9bb248bba0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab488eb5-f117-4e45-91b6-ee1ff1825517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-tableSearch--style</value>
      <webElementGuid>8887c28a-8870-42df-a302-9b87242f5016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d32ff249-c73e-4a5d-a201-ba9945e21cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CC 101</value>
      <webElementGuid>e9cd02b0-053d-4ce8-a1c8-ae82d9401333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>938ae7cb-189d-4f43-9b5a-a4753f864e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;body-side--container  wrapper&quot;]/div[@class=&quot;body-main--container&quot;]/div[@class=&quot;tableContainer-outer-container&quot;]/table[@class=&quot;table-responsive-sm mt-4 table-container responsiveTable&quot;]/thead[@class=&quot;table-header&quot;]/tr[@class=&quot;col&quot;]/th[@class=&quot;p-0 table-head--width&quot;]/div[@class=&quot;thead-form--container&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;col-md-auto&quot;]/div[@class=&quot;row table-head-search--container d-flex justify-content-center bg-white&quot;]/div[@class=&quot;col-10 px-2&quot;]/input[@class=&quot;input-tableSearch--style&quot;]</value>
      <webElementGuid>4bcea593-3241-4499-a879-27081e7b9bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[14]</value>
      <webElementGuid>d41826c0-3b88-451a-83ad-c22d9a8cf1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/table/thead/tr/th[13]/div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>3d512814-be4f-4397-876b-e64f153794de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[13]/div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>70c22170-e2a3-4ad1-b601-fca630cbdab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'CC 101']</value>
      <webElementGuid>a2e8f629-e764-4ad9-8f49-0dac709ca34d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
